### ISSUE TITLE
[EXC xxx] MissingMethodException: Method not found: 'UnityEngine.Texture2D.LoadImage'. 	SimpleLogistics.Core.OnGUI ()

### ISSUE THREAD

**Issue by zer0Kerbal** [Real-Gecko/KSP-SimpleLogistics#1]
KSP 1.7.2 with MH and BG - log is spammed with tens of thousands (if not more) of the following:

[EXC xxx] MissingMethodException: Method not found: 'UnityEngine.Texture2D.LoadImage'.
	SimpleLogistics.Core.OnGUI ()

**Comment by ghost** [comment]
Well, recompiling directly with 1.7.2 seems to work for me  
Can you try this? 
[SimpleLogistics.zip](https://github.com/Real-Gecko/KSP-SimpleLogistics/files/3317417/SimpleLogistics.zip)

**Comment by zer0Kerbal** [comment]
> 
> 
> Well, recompiling directly with 1.7.2 seems to work for me
> Can you try this?
> [SimpleLogistics.zip](https://github.com/Real-Gecko/KSP-SimpleLogistics/files/3317417/SimpleLogistics.zip)

thank you.
exactly what I was working on. :)
